# Generated by Django 3.0.3 on 2020-03-21 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import erp.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('uuid_employee', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('give_phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+48', max_length=128, region=None, unique=True)),
                ('date_of_employment', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=30)),
                ('hourly_rate', models.FloatField()),
            ],
            options={
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeesInProjects',
            fields=[
                ('connection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(db_column='uuid_employee', on_delete=django.db.models.deletion.CASCADE, to='erp.Employees')),
            ],
            options={
                'db_table': 'employees_in_projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('producer_name', models.CharField(max_length=30, unique=True)),
                ('contact_person', models.CharField(max_length=50)),
                ('give_phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+48', max_length=128, region=None, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('rabat', models.DecimalField(decimal_places=2, max_digits=4, validators=[erp.models.validate_zero])),
                ('delivery_time_days', models.CharField(default='-', max_length=15)),
            ],
            options={
                'db_table': 'producers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30, unique=True)),
                ('time_for_project_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[erp.models.validate_zero])),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15, validators=[erp.models.validate_zero])),
                ('employees', models.ManyToManyField(through='erp.EmployeesInProjects', to='erp.Employees')),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('tool_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geometry', models.CharField(choices=[('Square', 'Square'), ('Ball', 'Ball'), ('Corner radius', 'Corner radius')], default='Square', max_length=20)),
                ('material', models.CharField(choices=[('VHM', 'VHM'), ('HSS', 'HSS'), ('HSS-E', 'HSS-E')], default='VHM', max_length=20)),
                ('diameter_mm', models.DecimalField(decimal_places=2, max_digits=5, validators=[erp.models.validate_zero])),
                ('shank_diameter_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[erp.models.validate_zero])),
                ('tool_radius_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[erp.models.validate_zero])),
                ('tool_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[erp.models.validate_zero])),
                ('working_part_length_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[erp.models.validate_zero])),
                ('compensation_mm', models.FloatField(blank=True, null=True, validators=[erp.models.validate_zero])),
                ('status', models.CharField(choices=[('Can be_use', 'Can be use'), ('Needs sharpening', 'Needs sharpening'), ('Utilize the tool', 'Utilize the tool')], default='Can be use', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[erp.models.validate_zero])),
                ('date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('producer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='erp.Producers', validators=[erp.models.validate_zero])),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='erp.Projects')),
            ],
            options={
                'db_table': 'tools',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='employeesinprojects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Projects'),
        ),
    ]
